version: "3.8"
services:
  web:
    container_name: apache2
    build:
      context: .
      dockerfile: ./docker/apache2/Dockerfile  
    ports:
      - "8000:80"
  php:
    container_name: php
    extra_hosts:
        host.docker.internal: host-gateway
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./app:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  mysql:
    image: mariadb:latest
    ports:
      - "33060:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: project_db
      MARIADB_USER: project
      MARIADB_PASSWORD: project
    networks:
      - local-network
  phpmyadmin:
    depends_on:
     - mysql
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      MARIADB_ROOT_PASSWORD: root
    networks:
      - local-network

networks:
  local-network:


